import type { Metadata } from "next";
import { Anta } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const anta = Anta({
  display: "swap",
  weight: "400",
  variable: "--font-anta",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anta.variable} antialiased`}>
        <Header />
        <div className="container-main font-[var(--font-anta)]">{children}</div>
        <div id="portal-root" />
      </body>
    </html>
  );
}
