import type { Metadata } from "next";
import { Anta, PT_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const anta = Anta({
  display: "swap",
  weight: "400",
  variable: "--font-anta",
  subsets: ["latin"],
});

const ptSans = PT_Sans({
  display: "swap",
  weight: ["400", "700"],
  variable: "--font-pt-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${anta.variable} ${ptSans.variable}`}>
      <body className="antialiased">
        <Header />
        <div>{children}</div>
        <div id="portal-root" />
      </body>
    </html>
  );
}
